### ISSUE TITLE
[Suggestion] Replace spectator mode with normal fly

### ISSUE THREAD

**Issue by MrNinja008** [ItsMax123/StaffMode#10]
A suggestion to improve Vanish 😌
• Night vision effect for Vanished staff
• Stops you from picking up items when you are vanished
• Option to disable damage when vanished
• Option to allow survival fly when vanished

**Comment by ItsMax123** [comment]
Ill add the night vision but you already cant pick up items when in spectator mode, you can hit or be hit in spectator mode. And when doing "/staffmode" it puts you in spectator mode. 
Also what do you mean by survival fly? Do you want me to replace spectator mode with vanish and fly so staff cant go through blocks?
