### ISSUE TITLE
[suggestions] Add

### ISSUE THREAD

**Issue by Willtom999** [ItsMax123/StaffMode#3]
Add Staffchat mode for staff

**Comment by ItsMax123** [comment]
Implemented in commit https://github.com/ItsMax123/StaffMode/commit/b3ac6644c13c1d4253a225d9ac8a3672ffd4c201
Click here for direct poggit download: https://poggit.pmmp.io/ci/ItsMax123/StaffMode/StaffMode/dev:26
Remember not to download directly from github unless you know how to setup virions.
"/staffchat"
