### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by llPushkarSinghll** [ItsMax123/StaffMode#5]
[Mon_Jul_26-12.47.53-WIB_2021.log](https://github.com/ItsMax123/StaffMode/files/6875916/Mon_Jul_26-12.47.53-WIB_2021.log)

**Comment by ItsMax123** [comment]
Can you explain how this happened? What did you do before it crashed?

**Comment by llPushkarSinghll** [comment]
> Can you explain how this happened? What did you do before it crashed?

I think i left the server in staff mode

**Comment by ItsMax123** [comment]
Does it happen every time you logout in staffmode?

**Comment by ItsMax123** [comment]
https://poggit.pmmp.io/ci/ItsMax123/StaffMode/StaffMode/dev:31
This might fix it, im still not 100% sure why it crashed tho.

**Comment by llPushkarSinghll** [comment]
> https://poggit.pmmp.io/ci/ItsMax123/StaffMode/StaffMode/dev:31
> This might fix it, im still not 100% sure why it crashed tho.
> Keep me informed

Its fixed but when we rejoin we can fly in survival

**Comment by ItsMax123** [comment]
When you join back are you in gamemode survival or in spectator mode?

**Comment by llPushkarSinghll** [comment]
> When you join back are you in gamemode survival or in spectator mode?

Survival but we can fly

**Comment by ZZWILLIAMXXTrue** [comment]
This bug hasnt been fixed

**Comment by ItsMax123** [comment]
Fixed in commit 9da74f2
Download here: https://poggit.pmmp.io/ci/ItsMax123/StaffMode/StaffMode/dev:42
